export const LIST_DISCOUNTS_REQUEST = 'LIST_DISCOUNTS_REQUEST'
export const LIST_DISCOUNTS_SUCCESS = 'LIST_DISCOUNTS_SUCCESS'
export const LIST_DISCOUNTS_FAIL = 'LIST_DISCOUNTS_FAIL'
export const LIST_DISCOUNTS_ERROR_RESET = 'LIST_DISCOUNTS_ERROR_RESET'

export const DETAILS_DISCOUNT_REQUEST = 'DETAILS_DISCOUNT_REQUEST'
export const DETAILS_DISCOUNT_SUCCESS = 'DETAILS_DISCOUNT_SUCCESS'
export const DETAILS_DISCOUNT_FAIL = 'DETAILS_DISCOUNT_FAIL'
export const DETAILS_DISCOUNT_SUCCESS_RESET = 'DETAILS_DISCOUNT_SUCCESS_RESET'
export const DETAILS_DISCOUNT_RESET = 'DETAILS_DISCOUNT_RESET'

export const SAVE_MANAGED_DISCOUNT_REQUEST = 'SAVE_MANAGED_DISCOUNT_REQUEST'
export const SAVE_MANAGED_DISCOUNT_UPLOADING = 'SAVE_MANAGED_DISCOUNT_UPLOADING'
export const SAVE_MANAGED_DISCOUNT_SUCCESS = 'SAVE_MANAGED_DISCOUNT_SUCCESS'
export const SAVE_MANAGED_DISCOUNT_FAIL = 'SAVE_MANAGED_DISCOUNT_FAIL'
export const SAVE_MANAGED_DISCOUNT_RESET = 'SAVE_MANAGED_DISCOUNT_RESET'

export const DELETE_MANAGED_DISCOUNT_REQUEST = 'DELETE_MANAGED_DISCOUNT_REQUEST'
export const DELETE_MANAGED_DISCOUNT_SUCCESS = 'DELETE_MANAGED_DISCOUNT_SUCCESS'
export const DELETE_MANAGED_DISCOUNT_FAIL = 'DELETE_MANAGED_DISCOUNT_FAIL'
export const DELETE_MANAGED_DISCOUNT_RESET = 'DELETE_MANAGED_DISCOUNT_RESET'

export const LIST_DISCOUNT_RATE_REQUEST = 'LIST_DISCOUNT_RATE_REQUEST'
export const LIST_DISCOUNT_RATE_SUCCESS = 'LIST_DISCOUNT_RATE_SUCCESS'
export const LIST_DISCOUNT_RATE_FAIL = 'LIST_DISCOUNT_RATE_FAIL'

export const SAVE_DISCOUNT_RATE_REQUEST = 'SAVE_DISCOUNT_RATE_REQUEST'
export const SAVE_DISCOUNT_RATE_SUCCESS = 'SAVE_DISCOUNT_RATE_SUCCESS'
export const SAVE_DISCOUNT_RATE_FAIL = 'SAVE_DISCOUNT_RATE_FAIL'

export const DELETE_DISCOUNT_RATE_REQUEST = 'DELETE_DISCOUNT_RATE_REQUEST'
export const DELETE_DISCOUNT_RATE_SUCCESS = 'DELETE_DISCOUNT_RATE_SUCCESS'
export const DELETE_DISCOUNT_RATE_FAIL = 'DELETE_DISCOUNT_RATE_FAIL'

export const LIST_DISCOUNT_COMMENT_REQUEST = 'LIST_DISCOUNT_COMMENT_REQUEST'
export const LIST_DISCOUNT_COMMENT_SUCCESS = 'LIST_DISCOUNT_COMMENT_SUCCESS'
export const LIST_DISCOUNT_COMMENT_FAIL = 'LIST_DISCOUNT_COMMENT_FAIL'

export const SAVE_DISCOUNT_COMMENT_REQUEST = 'SAVE_DISCOUNT_COMMENT_REQUEST'
export const SAVE_DISCOUNT_COMMENT_SUCCESS = 'SAVE_DISCOUNT_COMMENT_SUCCESS'
export const SAVE_DISCOUNT_COMMENT_FAIL = 'SAVE_DISCOUNT_COMMENT_FAIL'

export const DELETE_DISCOUNT_COMMENT_REQUEST = 'DELETE_DISCOUNT_COMMENT_REQUEST'
export const DELETE_DISCOUNT_COMMENT_SUCCESS = 'DELETE_DISCOUNT_COMMENT_SUCCESS'
export const DELETE_DISCOUNT_COMMENT_FAIL = 'DELETE_DISCOUNT_COMMENT_FAIL'
