export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const SIGNIN_USER_REQUEST = 'SIGNIN_USER_REQUEST'
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS'
export const SIGNIN_USER_FAIL = 'SIGNIN_USER_FAIL'

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'

export const LOGOUT_USER = 'LOGOUT_USER'

export const LIST_USER_MESSAGE_ERROR_RESET = 'LIST_USER_MESSAGE_ERROR_RESET'

export const SEND_USER_CONFIRMATION_LINK_REQUEST = 'SEND_USER_CONFIRMATION_LINK_REQUEST'
export const SEND_USER_CONFIRMATION_LINK_SUCCESS = 'SEND_USER_CONFIRMATION_LINK_SUCCESS'
export const SEND_USER_CONFIRMATION_LINK_FAIL = 'SEND_USER_CONFIRMATION_LINK_FAIL'
export const SEND_USER_CONFIRMATION_LINK_RESET = 'SEND_USER_CONFIRMATION_LINK_RESET'

export const CONFIRM_USER_REQUEST = 'CONFIRM_USER_REQUEST'
export const CONFIRM_USER_SUCCESS = 'CONFIRM_USER_SUCCESS'
export const CONFIRM_USER_FAIL = 'CONFIRM_USER_FAIL'

export const SEND_PASSWORD_RESET_LINK_REQUEST = 'SEND_PASSWORD_RESET_LINK_REQUEST'
export const SEND_PASSWORD_RESET_LINK_SUCCESS = 'SEND_PASSWORD_RESET_LINK_SUCCESS'
export const SEND_PASSWORD_RESET_LINK_FAIL = 'SEND_PASSWORD_RESET_LINK_FAIL'
export const SEND_PASSWORD_RESET_LINK_RESET = 'SEND_PASSWORD_RESET_LINK_RESET'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'
export const RESET_PASSWORD_RESET = 'RESET_PASSWORD_RESET'

export const LIST_USERS_REQUEST = 'LIST_USERS_REQUEST'
export const LIST_USERS_SUCCESS = 'LIST_USERS_SUCCESS'
export const LIST_USERS_FAIL = 'LIST_USERS_FAIL'
export const LIST_USERS_ERROR_RESET = 'LIST_USERS_ERROR_RESET'

export const DELETE_MANAGED_USER_REQUEST = 'DELETE_MANAGED_USER_REQUEST'
export const DELETE_MANAGED_USER_SUCCESS = 'DELETE_MANAGED_USER_SUCCESS'
export const DELETE_MANAGED_USER_FAIL = 'DELETE_MANAGED_USER_FAIL'
export const DELETE_MANAGED_USER_ERROR_RESET = 'DELETE_MANAGED_USER_ERROR_RESET'
export const DELETE_MANAGED_USER_RESET = 'DELETE_MANAGED_USER_RESET'

export const CHANGE_USER_RANK_REQUEST = 'CHANGE_USER_RANK_REQUEST'
export const CHANGE_USER_RANK_SUCCESS = 'CHANGE_USER_RANK_SUCCESS'
export const CHANGE_USER_RANK_FAIL = 'CHANGE_USER_RANK_FAIL'
export const CHANGE_USER_RANK_RESET = 'CHANGE_USER_RANK_RESET'

export const LIST_USER_DATA_REQUEST = 'LIST_USER_DATA_REQUEST'
export const LIST_USER_DATA_SUCCESS = 'LIST_USER_DATA_SUCCESS'
export const LIST_USER_DATA_FAIL = 'LIST_USER_DATA_FAIL'
